import Head from "next/head";
import Link from "next/link";

export default function CatalogPage() {
  return <main>
    <Head>
      <title>Catalog | Doorastos</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h2>Catalog is here</h2>
    <Link href='/'>yooo</Link>

  </main>
}
