import Hero from '@/components/mainPageComponents/hero';
import Head from 'next/head'

const MainPage: React.FC = () => {
  return <>
    <Head>
      <title>Doorastos</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Hero />
    </main>
  </>
}
export default MainPage;