import AdditionalSecurity from '@/components/mainPageComponents/additionalSecurity';
import Advantages from '@/components/mainPageComponents/advantages';
import CompanyName from '@/components/mainPageComponents/companyName';
import ForWhat from '@/components/mainPageComponents/forWhat';
import Hero from '@/components/mainPageComponents/hero';
import QualityDifferences from '@/components/mainPageComponents/qualityDifferences';
import UniqueOffer from '@/components/mainPageComponents/uniqueOffer';
import Head from 'next/head'

const MainPage: React.FC = () => {
  return <>
    <Head>
      <title>Doorastos</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Hero />
      <UniqueOffer />
      <Advantages />
      <CompanyName />
      <ForWhat />
      <QualityDifferences />
      <AdditionalSecurity />
    </main>
  </>
}
export default MainPage;